### ISSUE TITLE
初步完成Product模块

### ISSUE THREAD

**Issue by jayjiahua** [jayjiahua/Cinpockema#3]
Product模块包括两个实体，场次(Screening)和电影票(Ticket)
screening需要引用电影(Movie)与影厅(Hall)
ticket需要引用screening和seat

相应的api应该有：
Screening
1. 查看特定电影院的场次
2. 增加场次
3. 修改场次
4. 删除场次

Ticket
增删改查

注意：操作之前应确认影院是否有该电影正在上映

**Comment by jayjiahua** [comment]
有以下几点需要改进：
1.  url前缀无需再加/product前缀
2. url设计应遵循restful的规则，例如：`/screenings/{cinemaId}`是不规范的，因为screenings后面跟的id应该是对应screenings资源的id，因此应该改为`/cinemas/{cinemaid}/screenings` 或者使用query string `/screenings?cinemaId=xxx` (这是GET方法，POST方法将数据放在请求体中，但无论使用什么请求方法，都是使用@RequestParam注解读取参数)。
3. 在DataInitHelper加上初始化数据，便于测试

**Comment by jayjiahua** [comment]
对于post请求，举个例子

```
@RequestMapping(value = {"/screenings"}, method = RequestMethod.POST)
@ResponseStatus(value = HttpStatus.CREATED)
@PreAuthorize("hasAuthority('admin')")
public Screening createScreening(@Valid @RequestBody Screening screening, @RequestParam("hallId") long hallId, @RequestParam("movieId") long movieId) {
    Hall hall = cinemaService.getHallById(hallId);
    Movie movie = movieService.getMovieById(movieId);
    return productService.createScreening(screening, hall, movie);
}
```

亲测可行，可以通过http://localhost:8080/api/product/screenings?hallId=1&movieId=1 这样的url（使用了查询字符串）来发送post请求，而RequestBody不需要改变，原来的@PathVariable改为@RequestParam即可

**Comment by fangshj** [comment]
我之前试过这样做，但好像在curl时第二个参数会get不到，而且在POST请求用query string并不常用，也不太规范，比较常用的做法还是将参数放在dataBody里，所以我还是将hallId及movieId放到了dataBody里了。

**Comment by fangshj** [comment]
第二个参数读不到应该是&的转义问题

**Comment by jayjiahua** [comment]
如果是放在body的话，那么传入的对象就无法反序列化了吧？...

**Comment by fangshj** [comment]
我改了实体类

**Comment by fangshj** [comment]
在screening类里加了hallId和movieId，这样就可以反序列化了。

**Comment by jayjiahua** [comment]
但是其实多出来的这两个字段是没有用的呀...就为了适应它的能够被反序列化，感觉不太好吧，如果非要这样做的话，就加个`@Transient`注解，不对其进行持久化

不过，我还是建议在实体的类声明加上注解`@JsonIgnoreProperties(ignoreUnknown=true)`，在反序列化时就会自动屏蔽不存在的field了。

**Comment by fangshj** [comment]
好的，我回去后加一下。修改实体类是不太妥，话说有其他解决方法吗？

**Comment by jayjiahua** [comment]
=_=上面说了，给类加注解`@JsonIgnoreProperties(ignoreUnknown=true)`就好，那不需要修改实体类了

**Comment by fangshj** [comment]
加注解@JsonIgnoreProperties(ignoreUnknown=true)的话，用@requestParam是读不了hallId和movieId的，我原本是用实体类新增的getter方法读的。
